function(AddSourcesToTarget target)
    #cmake_print_variables(target)
    foreach(arg IN LISTS ARGN)
        #cmake_print_variables(arg)
        target_sources(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${arg}")
    endforeach()
endfunction()
